import 'package:flutter/material.dart';
import 'screening_data.dart';

/// Menopause/Perimenopause screening — SD-27 to SD-34 · Greene Climacteric Scale
final menopauseConfig = ScreeningConfig(
  conditionType: 'Menopause',
  conditionTag: 'Perimenopause · Greene Climacteric Scale',
  intro: ScreeningIntro(
    emoji: '🌸',
    label: 'Perimenopause Screening',
    titleBefore: 'Check your\n',
    titleHighlight: 'menopause',
    titleAfter: ' symptoms',
    subtitle: '6 questions — based on the Greene Climacteric Scale',
    accentColor: const Color(0xFF6DC55A),
    accentBgLight: const Color(0xFFEAF7E4),
    accentBgDark: const Color(0xFFEAF7E4),
    checkItems: const [
      ScreeningCheckItem(title: 'Hot flushes & night sweats', subtitle: 'Sudden warmth, flushing, or sweating'),
      ScreeningCheckItem(title: 'Mood, anxiety & sleep', subtitle: 'Emotional changes and sleep quality'),
      ScreeningCheckItem(title: 'Joint pain & menstrual changes', subtitle: 'Physical symptoms and cycle changes'),
    ],
    disclaimer: 'Perimenopause is confirmed through clinical assessment and may include hormone tests. Please consult your doctor if results suggest perimenopause symptoms.',
  ),
  questions: const [
    ScreeningQuestion(
      questionText: 'Hot flushes or sudden feelings of\n',
      questionHighlight: 'heat?',
      subtitle: '',
      options: [
        'Not at all',
        'A little — once or twice a week',
        'Quite a bit — several times a week',
        'Extremely — daily or multiple times',
      ],
      researchNote: "Hot flushes occur in up to 80% of women during perimenopause. The Greene Climacteric Scale measures frequency and intensity as they are directly caused by falling oestrogen levels affecting the hypothalamic thermostat.",
      riskOptionIndices: [1, 2, 3],
    ),
    ScreeningQuestion(
      questionText: 'Sweating at ',
      questionHighlight: 'night',
      subtitle: 'that disrupts your sleep?',
      options: [
        'Not at all',
        'Occasionally — wakes me up sometimes',
        'Quite often — most nights',
        'Severely — soaks bedding, major disruption',
      ],
      researchNote: 'Night sweats are hot flushes occurring during sleep. They significantly disrupt sleep quality and are one of the most common and distressing symptoms of perimenopause.',
      riskOptionIndices: [1, 2, 3],
    ),
    ScreeningQuestion(
      questionText: 'Feeling ',
      questionHighlight: 'irritable, anxious or low in mood?',
      subtitle: '',
      options: [
        'Not at all',
        'Mildly — noticeable but manageable',
        'Quite a bit — affecting daily life',
        'Severely — significantly impacting relationships',
      ],
      researchNote: 'Mood changes in perimenopause are caused by fluctuating oestrogen affecting serotonin and other neurotransmitters. The Greene Scale captures both anxiety and depressive symptoms as a cluster.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: 'Difficulty ',
      questionHighlight: 'sleeping',
      subtitle: 'unrelated to night sweats?',
      options: [
        'Not at all',
        'Occasionally hard to fall or stay asleep',
        'Often — most nights affected',
        'Severely — chronic sleep disruption',
      ],
      researchNote: 'Sleep disturbance in perimenopause occurs independently of night sweats due to hormonal changes affecting sleep architecture. The Greene Scale distinguishes this from sweat-related sleep disruption.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: '',
      questionHighlight: 'Joint or muscle pain',
      subtitle: 'or stiffness?',
      options: [
        'Not at all',
        'Mild — occasional stiffness',
        'Moderate — regular discomfort',
        'Severe — limits daily movement',
      ],
      researchNote: 'Musculoskeletal symptoms affect up to 50% of perimenopausal women. Oestrogen has anti-inflammatory properties — as levels drop, joint inflammation increases, causing achiness and stiffness.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: 'Changes in your ',
      questionHighlight: 'menstrual cycle',
      subtitle: '— lighter, heavier or irregular?',
      options: [
        'Cycles still regular and normal',
        'Some irregularity — occasional changes',
        'Noticeably irregular — skipping months',
        'Periods have stopped or nearly stopped',
      ],
      researchNote: 'Menstrual cycle changes are the defining feature of perimenopause. The Greene Scale includes this to correlate cycle changes with other symptoms, helping establish whether symptoms are hormonally driven.',
      riskOptionIndices: [1, 2, 3],
    ),
  ],
  result: const ScreeningResultConfig(
    highTitle: 'Symptoms consistent with perimenopause',
    highBody: 'Your answers indicate several common perimenopausal symptoms. This is a natural transition — not an illness — but the right support makes a significant difference to quality of life.',
    moderateTitle: 'Some perimenopausal symptoms present',
    moderateBody: 'You reported some patterns that could indicate perimenopause. Tracking these over time will help you and your doctor understand the pattern.',
    lowTitle: 'Fewer perimenopause indicators found',
    lowBody: 'Your answers show fewer typical perimenopausal symptoms at this time. Symptoms can develop gradually — retake this screening if you notice changes.',
    highNextSteps: [
      'Add menopause-friendly program to your profile',
      'Anti-inflammatory diet and hormone-supporting nutrition',
      'Low-impact workouts suitable for this phase',
      'Track hot flush frequency and sleep quality',
    ],
    lowNextSteps: [
      'Track your cycle and symptoms in Fit Her',
      'Retake the screening in 3 months or if symptoms develop',
      'Speak to your doctor if you have any concerns',
    ],
    ctaButtonText: 'Book a gynaecologist consultation →',
  ),
  moderateThreshold: 4,
  highThreshold: 7,
);
