import 'package:flutter/material.dart';
import 'screening_data.dart';

/// Postpartum screening — SD-15 to SD-26 · Edinburgh Postnatal Depression Scale (EPDS)
final postpartumConfig = ScreeningConfig(
  conditionType: 'Postpartum',
  conditionTag: 'Postpartum · EPDS',
  intro: ScreeningIntro(
    emoji: '🤱',
    label: 'Postpartum Wellness',
    titleBefore: 'How are you feeling\n',
    titleHighlight: 'after birth?',
    subtitle: "10 questions about how you've felt this past week. All answers are private.",
    accentColor: const Color(0xFF6DC55A),
    accentBgLight: const Color(0xFFEAF7E4),
    accentBgDark: const Color(0xFFEAF7E4),
    checkItems: const [
      ScreeningCheckItem(title: 'Mood, enjoyment & anxiety this week', subtitle: 'Emotional wellbeing indicators'),
      ScreeningCheckItem(title: 'Sleep, coping & feeling overwhelmed', subtitle: 'Daily functioning assessment'),
      ScreeningCheckItem(title: 'Sadness, crying & wellbeing', subtitle: 'Core depression indicators'),
    ],
    disclaimer: 'This screening is based on the Edinburgh Postnatal Depression Scale. It is not a clinical diagnosis. If you are struggling, please reach out to a healthcare provider immediately.',
  ),
  questions: const [
    ScreeningQuestion(
      questionText: 'I have been able to ',
      questionHighlight: 'laugh',
      subtitle: 'and see the funny side of things',
      options: [
        'As much as I always could',
        'Not quite so much now',
        'Definitely not so much now',
        'Not at all',
      ],
      researchNote: 'Reduced capacity for enjoyment, including humour, is an early indicator of postpartum depression. The EPDS uses this as a gentler opening question that feels less clinical.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: 'I have looked forward with ',
      questionHighlight: 'enjoyment',
      subtitle: 'to things',
      options: [
        'As much as I ever did',
        'Rather less than I used to',
        'Definitely less than I used to',
        'Hardly at all',
      ],
      researchNote: 'Anhedonia — the inability to anticipate pleasure — is a core symptom of depression. This question measures whether the mother can still feel hope and positive anticipation.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: 'I have blamed myself ',
      questionHighlight: 'unnecessarily',
      subtitle: 'when things went wrong',
      options: [
        'Yes, most of the time',
        'Yes, some of the time',
        'Not very often',
        'No, never',
      ],
      researchNote: 'Excessive self-blame is a hallmark of postpartum depression. New mothers often experience guilt and self-criticism as depression amplifies perceived failures in parenting.',
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'I have been ',
      questionHighlight: 'anxious or worried',
      subtitle: 'for no good reason',
      options: [
        'No, not at all',
        'Hardly ever',
        'Yes, sometimes',
        'Yes, very often',
      ],
      researchNote: 'Postpartum anxiety frequently co-occurs with PPD. Persistent worry without clear cause — especially about the baby\'s health or safety — is a key indicator assessed by the EPDS.',
      riskOptionIndices: [2, 3],
    ),
    ScreeningQuestion(
      questionText: 'I have felt ',
      questionHighlight: 'scared or panicky',
      subtitle: 'for no very good reason',
      options: [
        'Yes, quite a lot',
        'Yes, sometimes',
        'No, not much',
        'No, not at all',
      ],
      researchNote: 'Panic symptoms in the postpartum period can indicate anxiety disorder alongside depression. The EPDS captures this to distinguish pure depression from mixed anxiety-depression.',
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'Things have been getting ',
      questionHighlight: 'on top of me',
      subtitle: '',
      options: [
        "Yes, most of the time I haven't been able to cope",
        "Yes, sometimes I haven't been coping",
        'No, most of the time I have coped quite well',
        'No, I have been coping as well as ever',
      ],
      researchNote: 'Feeling overwhelmed and unable to cope is one of the strongest predictors of PPD severity. This question assesses the functional impact of symptoms on daily life.',
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'I have been so unhappy that I have had ',
      questionHighlight: 'difficulty sleeping',
      subtitle: '',
      options: [
        'Yes, most of the time',
        'Yes, sometimes',
        'Not very often',
        'No, not at all',
      ],
      researchNote: "Sleep disturbance caused by emotional distress — distinct from normal newborn sleep disruption — is an important PPD indicator. The EPDS specifically asks about unhappiness-related sleep difficulty.",
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'I have felt ',
      questionHighlight: 'sad or miserable',
      subtitle: '',
      options: [
        'Yes, most of the time',
        'Yes, quite often',
        'Not very often',
        'No, not at all',
      ],
      researchNote: 'Core low mood is the central feature of postpartum depression. While sadness alone doesn\'t diagnose PPD, its frequency and intensity across the 7-day window is critical information.',
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'I have been so unhappy that I have been ',
      questionHighlight: 'crying',
      subtitle: '',
      options: [
        'Yes, most of the time',
        'Yes, quite often',
        'Only occasionally',
        'No, never',
      ],
      researchNote: "Frequent unexplained crying in the postpartum period — beyond the 'baby blues' which resolve within 2 weeks — is a strong indicator of PPD warranting clinical assessment.",
      riskOptionIndices: [0, 1],
    ),
    ScreeningQuestion(
      questionText: 'The thought of ',
      questionHighlight: 'harming myself',
      subtitle: 'has occurred to me',
      options: [
        'Yes, quite often',
        'Sometimes',
        'Hardly ever',
        'Never',
      ],
      researchNote: "Question 10 is the most critical EPDS question. Any answer other than 'Never' triggers an immediate recommendation to seek professional help. This is handled with care and crisis resources are always shown.",
      riskOptionIndices: [0, 1, 2],
    ),
  ],
  result: const ScreeningResultConfig(
    highTitle: 'Your score suggests you may need support',
    highBody: 'Your answers indicate you may be experiencing symptoms consistent with postpartum depression. This is very common — 1 in 5 new mothers experience PPD. You are not alone and support is available.',
    moderateTitle: 'Some indicators worth monitoring',
    moderateBody: 'You reported some symptoms that are common in the postpartum period but worth keeping an eye on. If they persist or worsen, please seek support.',
    lowTitle: 'Fewer PPD indicators this week',
    lowBody: 'Your answers show fewer signs of postpartum depression this week. Postpartum wellbeing can change — continue to check in weekly and speak to a doctor if you have any concerns.',
    highNextSteps: [
      'Add postpartum recovery program',
      'Gentle postpartum-safe workouts only',
      'Track mood and energy daily',
    ],
    lowNextSteps: [
      'Retake this screening weekly',
      'Track your mood daily in Fit Her',
      'Talk to a doctor if anything changes',
    ],
    ctaButtonText: 'Book a psychologist consultation →',
  ),
  moderateThreshold: 4,
  highThreshold: 7,
);
