// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCbZHjGvtJwFl-IrTCdimslfTCGe4GPAG4",
      authDomain: "fither-e7a36.firebaseapp.com",
      projectId: "fither-e7a36",
      storageBucket: "fither-e7a36.firebasestorage.app",
      messagingSenderId: "591042819842",
      appId: "1:591042819842:web:5bb1f96304b2b82f77f41b",
      measurementId: "G-HR4HD798HX"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrH8hJ_VE_VYRj4Kx3anZ4hl_0ypfxzvU',
    appId: '1:591042819842:android:b48deab996674d0e77f41b',
    messagingSenderId: '591042819842',
    projectId: 'fither-e7a36',
    storageBucket: 'fither-e7a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpuo9tWgtl9ad88VkuSwPNAXTMwjF9PE',
    appId: '1:591042819842:ios:88c99b8e4bb6314877f41b',
    messagingSenderId: '591042819842',
    projectId: 'fither-e7a36',
    storageBucket: 'fither-e7a36.appspot.com',
    iosBundleId: 'com.abtechnologies.fitHer',
  );

}